### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by kzscisoft** [FAIRDataPipeline/pyDataPipeline#13]
Currently the code assumes in many places that variables are in the correct state when accessing indexes etc, exceptions can be used to make sure the code is terminated when this is not the case, e.g.:
```
Traceback (most recent call last):
  File "/home/runner/work/FAIR-CLI/FAIR-CLI/python_example/src/org/fairdatapipeline/simpleModel/ext/SEIRSModelRun.py", line 13, in <module>
    initial_parameters = pipeline.link_read(handle, 'SEIRS_model/parameters')
  File "/home/runner/.cache/pypoetry/virtualenvs/fair-cli-AKUYcvYQ-py3.9/lib/python3.9/site-packages/org/fairdatapipeline/api/common/link_read.py", line 88, in link_read
    id = fdp_utils.extract_id(data_product_response[0]['object'])
IndexError: list index out of range
```

**Comment by kzscisoft** [comment]
Still some cases remain:
**Assuming Existence Indexes/Keys**
* All the files still have places where keys are being accessed in dictionaries under the assumption they exist in the given data.

**Extra: `&` is a binary operator, use `and`**
* https://github.com/FAIRDataPipeline/pyDataPipeline/blob/f919b2c61b0bdf9be5c5cc57247afa6cdf40cab1/fairdatapipeline/fdp_utils.py#L321
